version: '3.9'
services:
   mongodb:
      image: mongo
      restart: always
      container_name: mongodb
      ports:
         - "27017:27017"
   redis:
      image: redis
      restart: always
      environment:
         - ALLOW_EMPTY_PASSWORD=yes
      container_name: redis
      ports:
         -  "6379:6379"

   web:
      build: .
      container_name: api
      ports:
      - "8081:8081"
      links:
         -  redis



